id: IBAF3DAE4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T09:35:17+00:00'
last_modified: '2022-06-07T20:44:44.485749+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG20878
  title: འདས་ལོག་སངས་རྒྱས་ཆོས་འཛོམས་ཀྱི་རྣམ་ཐར་དད་པའི་སྤུ་ལོང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    2BD4:
      image_group_id: I1KG20945
      title: ''
      total_pages: 202
      order: 1
      base_file: 2BD4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
