id: P004166
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG20878
  title: འདས་ལོག་སངས་རྒྱས་ཆོས་འཛོམས་ཀྱི་རྣམ་ཐར་དད་པའི་སྤུ་ལོང་།
  author: ''
  volumes:
    353b8a51118642b192e8156b3693b6d0:
      image_group_id: I1KG20945
      title: ''
      volume_number: 1
      total_pages: 202
      base_file: v001.txt
